### ISSUE TITLE
I think another style of swagger-ui menus needed, not a theme.

### ISSUE THREAD

**Issue by lucups** [ostranme/swagger-ui-themes#18]
I like your themes very much, their colors are very cool!
But I think one thing is more important.

I hate the default style of swagger-ui's menus, I must to roll the mouse mid-wheels and click the small menus very frequently. It makes my hands tired. So, I think if we create a  left-sidebar , and put the menus on it, it will be popular !

**Comment by ostranme** [comment]
I'm assuming you want something similar to how http://tripit.github.io/slate/ does it with the left sidebar menu? I know there are random projects that kind of provide this for swagger like the one below: 

https://github.com/jensoleg/swagger-ui

I haven't found anything myself that I like yet so maybe it is worth trying to create a new template/theme for swagger UI.

**Comment by lucups** [comment]
Thanks very much for your help!  This project `jensoleg/swagger-ui` is the one that I want to find! 

I have been looking for it for a long time. I've tried the keywords `swagger ui theme`, `swagger ui style`, and none is what I want to find.  

Thank you very much again!

**Comment by ostranme** [comment]
Glad I could help! :+1:
