### ISSUE TITLE
Make SCSS Theme Files Available

### ISSUE THREAD

**Issue by codylawson** [ostranme/swagger-ui-themes#25]
Were these themes developed using a css preprocessor? Any chance the file might be made available? I really like the Flat top theme but want to slightly modify it to match brand colors.

Thanks

**Comment by ostranme** [comment]
@codylawson Unfortunately the themes were developed by hand with trial and error of vanilla css for quick implementations. Let me think about how to add scss support (and maybe less support). It basically requires nailing down all potential variables and mixins to use.  I agree with you on making this easier to modify brand colors if scss files were created.

**Comment by codylawson** [comment]
Yeah, it would be great if each theme was just a modified variables file that fed into several scss files for each component. It would simplify the creation of new themes and make customizing them more feasible.

I'm going to be trying my hand at this over the next week, I'll let you know what I find.

**Comment by ostranme** [comment]
Sounds good.  I'm open to collaborate on initial steps to support scss. It'd be nice to maybe plan it out and do a prototype.

Another thing to consider is to look into making swagger-ui support scss as well. I don't know what their position is on supporting scss or less but would interesting to push them in that direction.

**Comment by ostranme** [comment]
Closing issue for now. I don't see myself having the bandwidth or create scss variables for this project. Thanks for the suggestion!
