### ISSUE TITLE
define "swagger-ui html"

### ISSUE THREAD

**Issue by bardware** [ostranme/swagger-ui-themes#29]
Hi,

the instruction says to `place the desired stylesheet into the source of your swagger-ui html`
When I'm in swagger editor: how do I obtain my `swagger-ui html`? There's `Generate Client => html`  , `Generate Client => html2`, I can right click the right pane and `Save as`.

What is the right HTML page your CSS files style?

Best,
Bernhard Döbler

**Comment by ostranme** [comment]
Unfortunately swagger editor is a different tool then swagger-ui and these themes currently do not apply. The swagger editor project uses different css and html. These style sheets are really just for modifying swagger-ui projects.

**Comment by bardware** [comment]
OK. Thank you!
