### ISSUE TITLE
unable to load gif in version 2

### ISSUE THREAD

**Issue by EduardoJuliao** [ostranme/swagger-ui-themes#31]
When using the version 2 of the CSS, the loader gif is not found.

Changing line 883 from:
<code>
background-image: url('../images/throbber.gif');
</code>
To:
<code>
background-image: url('../images/throbber-gif');
</code>

solved the problem.

**Comment by ostranme** [comment]
I'll take a look to get that fixed. Thanks for the heads up.

**Comment by ostranme** [comment]
@EduardoJuliao Which version of swagger UI 2.x are you using. I'm currently looking into v2.2.10 and it loads the gif just fine. It might be a different between an older version of swagger ui 2.x that you are using.
