### ISSUE TITLE
Make feeling blue just a little bit more blue

### ISSUE THREAD

**Issue by Lynorics** [ostranme/swagger-ui-themes#32]
Hi, 

here are some suggestions to make _feeling blue_ just a little bit more blue. ;-)

```
.swagger-section #header {
	background-color: #0489bf;
}

.swagger-section .swagger-ui-wrap a {
	color: #00547f;
}

.swagger-section .swagger-ui-wrap pre {
	background-color: #f6f6fc;
}

.swagger-section .swagger-ui-wrap .model-signature pre:hover {
	background-color: #e6e6fc;
}
```

**Comment by ostranme** [comment]
I'll check this out soon, if you want to make a pull request I can check it out as well.

**Comment by Lynorics** [comment]
I will create a pull request soon.

**Comment by ostranme** [comment]
Feel free to submit a new theme with new blues. Closing issue for now as I want to keep the original colors of theme. Thanks!
