### ISSUE TITLE
Swagger UI as extension

### ISSUE THREAD

**Issue by AMoreaux** [ostranme/swagger-ui-themes#35]
If you can't insert the link in the source code, you can use the chrome extension : https://chrome.google.com/webstore/detail/swagger-ui-themes/mmbhchnmidfdfbecginjphmijieofngc

**Comment by ostranme** [comment]
That's pretty cool...thanks for sharing!

**Comment by ostranme** [comment]
@AMoreaux What are your thoughts on moving this link and adding a section to the README? That way the issue can close but have it live on the README.

**Comment by AMoreaux** [comment]
Sure 🙂

**Comment by ostranme** [comment]
Closing issue. Provided a link to a new section title "Community Driven Tools"  in the README with the chrome extension.
