### ISSUE TITLE
Can we integrate this with Swagger UI for Spring Boot?

### ISSUE THREAD

**Issue by RahulSDeshpande** [ostranme/swagger-ui-themes#39]

**Comment by ostranme** [comment]
Hey @RahulSDeshpande - I'll have to do some research as I don't have experience with Spring Boot. Let me know if you have any ideas...happy to try and help make this happen.

**Comment by RahulSDeshpande** [comment]
Thanks, @ostranme :)
I will get back.

**Comment by jefcolbi** [comment]
One year later.....

**Comment by ostranme** [comment]
@jefcolbi Feel free to submit a pull request if you want this feature - thanks!

**Comment by cc8t** [comment]
one year later 🥇

**Comment by ostranme** [comment]
> one year later 🥇

@rexeo-asia As stated above, if this a feature you would like, feel free to submit a PR or start a conversation on the implementation. If anyone has ideas please let me know I'm happy to try and help.

**Comment by ostranme** [comment]
Closing this issue since it's not related to this direct repo and library. I would recommend asking the question for SpringBoot or Swagger UI.
