### ISSUE TITLE
http://meostrander.com/swagger-ui-themes/ leads to some cheater site

### ISSUE THREAD

**Issue by 776166** [ostranme/swagger-ui-themes#40]
subj

**Comment by ostranme** [comment]
Updated...thanks!

**Comment by KurtMar** [comment]
The link still lives on in [https://www.npmjs.com/package/swagger-ui-themes](https://www.npmjs.com/package/swagger-ui-themes). Many people are probably clicking on the link and getting redirected to the scam site. This might constitute a 3.0.1 version npm release with the corrected README.md.

**Comment by ostranme** [comment]
I'll take a look at making this update soon. thanks for making me aware of this.

**Comment by ostranme** [comment]
@KurtMar Hopefully this is resolved...pushed v3.0.1 to npm. Let me know if you see anything else weird.
